global:
  namespace: spring-6-reactive-mongo

mongodb:
  port: 27017
  targetPort: 27017
  nodePort: 30017
  
  database: "sfg"
    
# We intentionally use this version.
# Versions 8.0.9 and 8.0.10 are not pulled correctly and are therefore not usable in Kubernetes.
# You can verify this manually via `docker pull` and `docker inspect`.
mongoImage:
  repository: mongo
  tag: "8.2.5"
  pullPolicy: IfNotPresent
debianSlimImage:
  repository: debian
  tag: "bullseye-20250610-slim"
  pullPolicy: IfNotPresent
